---
- name: Настройка кластера rabbitmq
  hosts: rabbitmq-cluster
#  vars:
#  vars_files: vars.yaml

  become: yes
  tasks:

#------- Настройки ОС ---------
  - name: Отключить автообновление
    replace:
      path: "/etc/apt/apt.conf.d/20auto-upgrades"
      regexp: '1'
      replace: '0'

  - name: Проверить часовой пояс Europe/Moscow
    community.general.timezone:
      name: Europe/Moscow

  - name: Ensure a locale exists
    community.general.locale_gen:
      name: C.UTF-8
      state: present

  - name: Update apt packages
    become: true
    apt:
      update_cache: yes
      cache_valid_time: 86400 #One day
#      upgrade: yes

#------- установка пакетов ------

  - name: "Проверить что пакеты установлены"
    apt:
      name:
        - rabbitmq-server
        - pip
        - mc
      state: present

  - name: Установить библиотеку pika
    pip:
      name:
        - pika

# --- файл hosts
  - name: добавить записи в файл hosts (вообще это не идемпотентно - нужно бы переделать может через replace)
    shell: >
      sudo echo "192.168.10.10 rabbitmq1" >> /etc/hosts &&
      sudo echo "192.168.10.11 rabbitmq2" >> /etc/hosts        

#--- настройки rabbitmq ---

  - name: enable rabbitmq plugins
    rabbitmq_plugin:
      names: rabbitmq_management,rabbitmq_tracing,rabbitmq_federation
      state: enabled
    become: yes
    become_user: rabbitmq      

  - name: ensure rabbitmq vhost / is present
    rabbitmq_vhost:
      name: /
      state: present

#------- Настройка кластера rabbitmq -----------------------------------------------

  - name: rabbitmq_clustering | ensure rabbits are stopped
    service:
      name: rabbitmq-server
      state: stopped

#  - name: rabbitmq_clustering | copy erlang cookie
#    template:
#      src: templates/erlang.cookie.j2
#      dest: /var/lib/rabbitmq/.erlang.cookie
#      owner: rabbitmq
#      group: rabbitmq
#      mode: 0400
#      backup: yes
#    no_log: True

  - name: создать файл erlang.cookie с куками
    shell: >
      sudo echo "12345" > /var/lib/rabbitmq/.erlang.cookie

  - name: rabbitmq_clustering | restarting rabbitmq-server to pick up new cookie
    service:
      name: rabbitmq-server
      state: started

  # the following 3 commands run on the secondary nodes only
  - name: rabbitmq_clustering | stopping rabbitmq app
    command: rabbitmqctl stop_app
    when: inventory_hostname != "rabbitmq1"

  - name: rabbitmq_clustering | resetting rabbitmq app
    command: rabbitmqctl reset
    when: inventory_hostname != "rabbitmq1"

  - name: rabbitmq_clustering | start rabbitmq app
    command: rabbitmqctl start_app
    when: inventory_hostname != "rabbitmq1"

  # The following commands run on the primary node
  - name: rabbitmq_clustering | stopping rabbitmq app
    command: rabbitmqctl stop_app
    when: inventory_hostname == "rabbitmq1"

    # resetting the app destroys user access
  - name: rabbitmq_clustering | resetting rabbitmq app
    command: rabbitmqctl reset
    when: inventory_hostname == "rabbitmq1"

  # while the playbook uses the primary/secondary nomenclature
  # it doesn't matter which node joins the cluster first or second...
  # we only have two nodes in this cluster. If there were more,
  # then ideally, we'd tell every secondary node to join the primary


  - name: rabbitmq_clustering | joining rabbitmq cluster
    tags: now
    command: rabbitmqctl join_cluster 'rabbit@rabbitmq2'
    register: cluster_joined
    when: inventory_hostname == "rabbitmq1"

  - name: rabbitmq_clustering | start rabbitmq app
    tags: now
    command: rabbitmqctl start_app
    when: inventory_hostname == "rabbitmq1"

  - name: rabbitmq_clustering | all the queues
    tags: now
    command: rabbitmqctl set_policy ha-all "" '{"ha-mode":"all","ha-sync-mode":"automatic"}'
    when: inventory_hostname == "rabbitmq1"

  - name: add rabbitmq user
    tags:
      - rabbitmq-users
    rabbitmq_user:
      user: "test"
      password: "passwd"
      tags: administrator,"rabbit"
      vhost: /
      configure_priv: .*
      write_priv: .*
      read_priv: .*
      state: present
    ignore_errors: yes
    when: inventory_hostname == "rabbitmq1"


#------------------------------------------------------

...
