version: '3.9'

services:
  rabbit1:
    image: bitnami/rabbitmq:latest
#    volumes:
# # #      - ./configs/elasticsearch/config.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
      # - ./docker_volumes/elasticsearch/data:/usr/share/elasticsearch/data
    environment:
      - RABBITMQ_DEFAULT_USER="user"
      - RABBITMQ_DEFAULT_PASS="12345"
    networks:
      - rabbit
    ports:
      - "5672:5672"
      - "15672:15672"
    restart: always



networks:
  rabbit:
    driver: bridge